### ISSUE TITLE
Tenancy Graph View - Error 500

### ISSUE THREAD

**Issue by teone** [open-cloud/xos#114]
I've noticed that when navigating to **Services > Tenancy Graph** (url: `http://0.0.0.0:9000/serviceGraph.png`) generate a 500 Error

**Comment by sbconsulting** [comment]
This looks like an issue with the pygraphviz package:

>>> import pygraphviz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/__init__.py", line 58, in <module>
    from .agraph import AGraph, Node, Edge, Attribute, ItemAttribute, DotError
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/agraph.py", line 26, in <module>
    from . import graphviz as gv
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 28, in <module>
    _graphviz = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/pygraphviz/graphviz.py", line 24, in swig_import_helper
    _mod = imp.load_module('_graphviz', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/pygraphviz/_graphviz.so: undefined symbol: Agundirected

**Comment by sbconsulting** [comment]
The following will repair it:

pip uninstall pygraphviz
pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
# restart the server
/opt/xos/scripts/openclound runserver

Note that graph will still be empty until there are at least two service objects and a tenancy relationship between them.

**Comment by sbconsulting** [comment]
Fixed.
