### ISSUE TITLE
observer cannot handle image names with space in it

### ISSUE THREAD

**Issue by caglar10ur** [open-cloud/xos#27]
and raises following exception

```
Step <class 'sync_slivers.SyncSlivers'> succeeded
INFO:planetstack.log:Executing step SyncNetworkSlivers
Executing step SyncNetworkSlivers
INFO:planetstack.log:sync'ing network slivers
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
ERROR: the playbook: /opt/opencloud/controller_images/Fedora could not be found

ERROR:planetstack.log:sync step failed! BEG TRACEBACK
Traceback (most recent call last):
  File "/root/xos/planetstack/observer/syncstep.py", line 123, in call
    self.sync_record(o)
  File "/opt/xos/observer/steps/sync_controller_images.py", line 37, in sync_record
    res = run_template('sync_controller_images.yaml', image_fields, path='controller_images', expected_num=1)
  File "/root/xos/planetstack/observer/ansible.py", line 89, in run_template
    raise Exception(error)
Exception
ERROR:planetstack.log:sync step failed! END TRACEBACK
INFO:planetstack.log:Step <class 'sync_controller_images.SyncControllerImages'> succeeded
Step <class 'sync_controller_images.SyncControllerImages'> succeeded
INFO:planetstack.log:Step <class 'sync_controller_images.SyncControllerImages'> is a leaf
```

**Comment by gwsapan** [comment]
Commit 258176e7 should have fixed this error in general.
