### ISSUE TITLE
/stats endpoint is either returning Internal Server Error or showing traces for non-existed controllers (lie princeton-beta)

### ISSUE THREAD

**Issue by caglar10ur** [open-cloud/xos#36]
```
[12/Feb/2015 13:49:54] "GET /observer HTTP/1.1" 200 134
Internal Server Error: /stats/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/xos/core/views/stats.py", line 12, in Stats
    controller = Controller.objects.filter(name=controller_name)[0]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 177, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
Internal Server Error: /stats/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/xos/core/views/stats.py", line 12, in Stats
    controller = Controller.objects.filter(name=controller_name)[0]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 177, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
Internal Server Error: /stats/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/xos/core/views/stats.py", line 12, in Stats
    controller = Controller.objects.filter(name=controller_name)[0]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 177, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
[12/Feb/2015 13:49:54] "GET /stats/?model_name=Sliver&pk=1&meter=network.incoming.bytes&controller_name=princeton-beta HTTP/1.1" 500 11860
[12/Feb/2015 13:49:54] "GET /stats/?model_name=Sliver&pk=1&meter=cpu&controller_name=princeton-beta HTTP/1.1" 500 11803
[12/Feb/2015 13:49:54] "GET /stats/?model_name=Sliver&pk=1&meter=network.outgoing.bytes&controller_name=princeton-beta HTTP/1.1" 500 11860
[12/Feb/2015 13:50:54] "GET /observer HTTP/1.1" 200 140
[12/Feb/2015 13:51:54] "GET /observer HTTP/1.1" 200 138
```

**Comment by sbconsulting** [comment]
Fixed. Error message will now be displayed in minidashboard.
