### ISSUE TITLE
AttributeError: 'unicode' object has no attribute 'auth_url'

### ISSUE THREAD

**Issue by caglar10ur** [open-cloud/xos#56]
```
INFO:xos.log:Step <class 'sync_controller_images.SyncControllerImages'> is a leaf
INFO:xos.log:Step <class 'sync_controller_site_privileges.SyncControllerSitePrivileges'> is a leaf
INFO:xos.log:Step <class 'sync_controller_sites.SyncControllerSites'> succeeded
Step <class 'sync_controller_sites.SyncControllerSites'> succeeded
INFO:xos.log:Step <class 'sync_slivers.SyncSlivers'> succeeded
Step <class 'sync_slivers.SyncSlivers'> succeeded
INFO:xos.log:Step <class 'sync_controller_users.SyncControllerUsers'> succeeded
Step <class 'sync_controller_users.SyncControllerUsers'> succeeded
ERROR:xos.log:sync step failed! BEG TRACEBACK
Traceback (most recent call last):
  File "/opt/xos/observer/syncstep.py", line 133, in call
    self.delete_record(o)
  File "/opt/xos/observer/steps/sync_controller_slices.py", line 73, in delete_record
    driver = OpenStackDriver().admin_driver(controller=controller_slice.controller.name)
  File "/opt/xos/openstack/driver.py", line 48, in admin_driver
    client = OpenStackClient(tenant=tenant, controller=controller, cacert=self.config.nova_ca_ssl_cert)
  File "/opt/xos/openstack/client.py", line 177, in __init__
    self.keystone = KeystoneClient(*args, **kwds)
  File "/opt/xos/openstack/client.py", line 70, in __init__
    Client.__init__(self, *args, **kwds)
  File "/opt/xos/openstack/client.py", line 42, in __init__
    self.url = controller.auth_url
AttributeError: 'unicode' object has no attribute 'auth_url'
ERROR:xos.log:sync step failed! END TRACEBACK
INFO:xos.log:Step <class 'sync_controller_slices.SyncControllerSlices'> succeeded
Step <class 'sync_controller_slices.SyncControllerSlices'> succeeded
INFO:xos.log:Step <class 'sync_network_slivers.SyncNetworkSlivers'> succeeded
Step <class 'sync_network_slivers.SyncNetworkSlivers'> succeeded
INFO:xos.log:Step <class 'sync_network_slivers.SyncNetworkSlivers'> is a leaf
INFO:xos.log:Waiting for event
```

**Comment by tmack-pl** [comment]
fixed in this commit https://github.com/open-cloud/xos/commit/60e1d81ab573699b1abd6918dfc8fc04c9ca4f13
